[package]
name = "justbus-rs"
version = "0.4.0-beta"
authors = ["Budi Syahiddin <me@inve.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.6"
serde = { version = "1.0" }
serde_json = "1.0"
cht-time = { path = "./cht", optional = true }
hashbrown-time = { path = "./hashbrown", optional = true }
parking_lot = { version = "0.11.0", optional = true}
justbus-utils = { path = "./justbus-utils" }
lta = "0.5.0-beta"
dashmap-time = { path = "./dashmap", optional = true}
env_logger = { version = "0.7.1", optional = true }
log = { version = "0.4.11", optional = true }
rustls = { version = "0.18", optional = true }
argh = "0.1.3"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"

[features]
default = []
cht = ["cht-time"]
swisstable = ["hashbrown-time", "parking_lot"]
nightly = ["parking_lot/nightly"]
dashmap = ["dashmap-time"]
tls = ["actix-web/rustls", "rustls"]
logging = ["env_logger", "log"]

[workspace]
members = [
    "cht",
    "hashbrown",
    "dashmap",
    "justbus-utils",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = true