[package]
name = "justbus-rs"
version = "0.1.0"
authors = ["Budi Syahiddin <budisyahiddin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lta = { git="https://github.com/BudiNverse/lta-rs.git", branch="master", features = ["async"] }
actix-web = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.9.0"
cht = "0.1.2"
actix-rt = "1.0.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = true