[package]
name = "justbus-rs"
version = "0.3.0"
authors = ["Budi Syahiddin <budisyahiddin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lta = { version = "0.4.0", features = ["async"] }
actix-web = "3"
serde = { version = "1.0" }
serde_json = "1.0"
cht-time = { path = "./cht", optional = true }
hashbrown-time = { path = "./hashbrown", optional = true }
parking_lot = { version = "0.11.0", optional = true}

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"

[features]
default = []
cht = ["cht-time"]
hashbrown = ["hashbrown-time", "parking_lot"]
nightly = ["parking_lot/nightly"]

[workspace]
members = [
    "cht",
    "hashbrown",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = true