[package]
name = "justbus-rs"
version = "0.3.0"
authors = ["Budi Syahiddin <me@inve.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = { version = "1.0" }
serde_json = "1.0"
cht-time = { path = "./cht", optional = true }
hashbrown-time = { path = "./hashbrown", optional = true }
parking_lot = { version = "0.11.0", optional = true}
internal_entry = { path = "./internal_entry" }
dashmap = { version = "3.11.10", optional = true }
lta = { git = "https://github.com/BudiNverse/lta-rs.git", branch = "async-traits", features = ["async"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"

[features]
default = []
cht = ["cht-time"]
hashbrown = ["hashbrown-time", "parking_lot"]
nightly = ["parking_lot/nightly"]
dashmap_cache = ["dashmap"]
openssl = []
rustls = []

[workspace]
members = [
    "cht",
    "hashbrown",
    "internal_entry"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = true